# Copyright (c) 2016-2023 Martin Donath <martin.donath@squidfunk.com>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

# Project information
site_name: Faculty - LMS Documentation
site_url:
site_author: SpaGreen Creative
site_description: >-
  A complete eLearning management system build for every edu-tech platform,
  which is committed to deliver effortless lms experience!


# Repository
repo_name:
repo_url:

# Copyright
copyright: Copyright &copy; 2019 - 2023 SpaGreen Creative

# Configuration
theme:
  name: material
  custom_dir: material/.overrides
  features:
    - navigation.footer
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - scheme: default
      primary: green
      accent: green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: green
      accent: green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Jost
    code: Roboto Mono
  favicon: assets/favicon.png
  logo: assets/logo.png

# Plugins
plugins:
  - glightbox:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'

# Hooks
hooks:
  - material/.overrides/hooks/translations.py

# Customization
extra:
  annotate:
    json: [.s2]
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/spagreen
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/spagreencreative
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/spagreenbd

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Home: index.md
  - Getting started:
    - Introducing: getting-started.md
    - Requirements: requirements.md
    - Installation: installation.md
  - Setup:
      - setup/index.md
      - General Setting: setup/general.md
      - Preference: setup/preference.md
      - Currency Setting: setup/currency.md
      - Email Setting: setup/email.md
      - Language Setting: setup/language.md
      - Cache Setting: setup/cache.md
      - Admin Panel Setting: setup/admin-panel.md
      - Firebase Setting: setup/firebase.md
      - Storage Setting: setup/storage.md
      - Chat Setting: setup/chat.md
      - Refund Setting: setup/refund.md
      - Misc. Setting: setup/misc.md
      - Payment Gateway:
        - setup/payment-gateway.md
      - SMS & OTP:
        - uses/sms-otp.md
  - Usage:
      - uses/index.md
      - Course:
        - uses/course-list.md
        - uses/course-category.md
        - uses/course-subject.md
        - uses/course-tags.md
        - uses/course-levels.md
        - uses/certificates.md
      - Manage Students:
        - uses/manage-students.md
      - Manage Instructors:
        - uses/manage-instructor.md
        - uses/add-instructor.md
      - Manage Organization:
        - uses/manage-organization.md
        - uses/add-organization.md
      - Manage Staff:
        - uses/manage-staff.md
        - uses/roles.md
      - Media Library:
        - uses/media-library.md
      - All Pages:
        - uses/all-pages.md
      - Blog:
        - uses/blog.md
      - Payment Gateway:
        - uses/payment-gateway.md
      - Refund:
        - uses/refund.md
      - Packages:
        - uses/packages.md
      - Payout:
        - uses/payout.md
      - Notification:
        - uses/notification.md
      - Support:
        - uses/support.md
      - Marketing:
        - uses/marketing.md
      - Reports:
        - uses/reports.md
      - Mobile App Settings:
        - uses/mobile-app-settings.md
      - CMS:
        - uses/cms.md
      - Website Settings:
        - uses/website-settings.md

  - Utility:
      - utility/index.md

  - Addon:
      - Addon:
          addon/index.md
  - Changelog:
      - changelog/index.md
  - Student App:
      - App Basics:
        - Recommendation: studentApp/recommendation.md
        - Installation: studentApp/installation.md
        - Prepare Flutter Environment: studentApp/prepare-flutter-environment.md

      - Common Setup:
        - Google Firebase Setup: studentApp/google-firebase-setup.md
        - Social Login Setup: studentApp/social-login-setup.md
        - Change Api Server Details: studentApp/change-api-server-details.md
        - Change App Logo: studentApp/change-app-logo.md
        - Change Splash Screen Logo: studentApp/change-splash-screen-logo.md

      - Android Setup:
        - Change App Name: studentApp/change-app-name.md
        - Change Android Luncher Icon: studentApp/chaneg-android-luncher-icon.md
        - Change Android Package Name: studentApp/change-android-package-name.md
        - Generate Debug APK: studentApp/generate-debug-apk.md
        - Generate Signed APK: studentApp/generate-signed-apk.md


      - IOS Setup:
        - Preliminaries: studentApp/preliminaries.md
        - Register App On AppStore: studentApp/register-app-appstore.md
        - Create Application Record on AppStore : studentApp/create-application-record.md
        - Review Xcode project settings:  studentApp/review-xcode-project-settings.md
        - Updating the app deployment version: studentApp/updating-app-development-version.md
        - Add an app icon: studentApp/add-an-app-icon.md

        - Build archive and Submit To AppStore: studentApp/build-archive-and-submit.md
        - Update the app build and version numbers: studentApp/update-app-build.md
        - Create An App Bundle: studentApp/create-app-bundle.md
        - Upload App Bundle To App Store Connect:  studentApp/upload-app-bundle.md
        - Updating the app deployment version: studentApp/update-app-development-version.md
        - Release your app on TestFlight: studentApp/release-on-testflight.md
        - Release your app to the App Store: studentApp/release-on-app-store.md














